import { BackHandler, StyleSheet } from "react-native";
import React from "react";
import { StatusBar } from "expo-status-bar";

export const Styles = (props) =>
  StyleSheet.create({
    ManageContainer: {
      height: "100%",
    },
    dateContainer: {
      padding: 10,
      backgroundColor: "#03588C",
    },
    DateText: {
      fontSize: 20,
      textAlign: "center",
      color: "white",
    },
    serviceContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 30,
      marginTop: 10,
      width: "100%",
    },
    ServiceText: {
      fontSize: 30,
      textAlign: "left",
      color: "black",
      fontWeight: "600",
    },
    jobdetailsContainer: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-start",
      alignItems: "center",
      textAlign: "center",
      margin: 5,
      borderWidth: 2,
      borderRadius: 5,
      borderColor: "grey",
    },
    carNameContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-evenly",
      width: "100%",
      marginBottom: 20,
    },
    CarTextStyleTopic: { fontSize: 25, width: 100 },
    CarTextStyleDash: { fontSize: 25, width: 10 },
    CarTextStyleData: { fontSize: 25, width: 160 },
    addressContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-evenly",
      width: "100%",
      marginBottom: 20,
    },
    addressTextStyleTopic: { fontSize: 25, width: 100 },
    addressTextStyleDash: { fontSize: 25, width: 10 },
    addressTextStyleData: { fontSize: 25, width: 160, margin: 0 },
    carAvailiableContainer: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
      flexDirection: "row",
      borderWidth: 2,
      borderRadius: 5,
      borderColor: "grey",
      margin: 5,
      padding: 4,
    },
    checkbox: {
      display: "flex",
    },
    interiornlightsContainer: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "column",
      margin: 5,
      padding: 4,
    },
    interiorLightsCheckBoc: {
      display: "flex",
      justifyContent: "flex-end",
      alignItems: "center",
      flexDirection: "row-reverse",
      borderWidth: 2,
      borderRadius: 5,
      borderColor: "grey",
      margin: 5,
      padding: 4,
      width: "100%",
    },
    imageContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-evenly",
      alignItems: "center",
      marginTop: 10,
    },
    logo: {
      width: 50,
      height: 50,
      borderWidth: 2,
      padding: 10,
      borderColor: "grey",
      borderRadius: 100,
    },
    logo2: {
      width: 150,
      height: 150,
      borderWidth: 1,
      padding: 10,
      borderColor: "grey",
      borderRadius: 100,
    },
    messageContainer: {
      margin: 10,
      marginTop: 30,
    },
    buttonContainer: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
    },
    saveButtom: {
      height: 40,
      width: 130,
      margin:5,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      borderWidth: 0,
      borderRadius: 0,
    },
  });
