import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  cleanerName: {
    fontSize: 20,
    textAlign: "center",
    padding: 10,
    backgroundColor: "#03588C",
    color: "white",
  },
  eventStyle: {
    width: 100,
    marginLeft: 0,
    borderRadius: 5,
  },
  DateViewContainer: {
    display: "flex",
    flexDirection: "row",

    justifyContent: "center",
    alignItems: "center",
    height: 80,
  },
  DateText: {
    fontSize: 20,
  },
  oneJobWashing: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#ADD9C5",
    margin: 5,
    marginRight: 10,
    marginLeft: 10,
    height: 100,
    justifyContent: "space-around",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "grey",
    borderRadius: 5,
  },
  oneJobSanitization: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#F2CAB3",
    margin: 5,
    marginRight: 10,
    marginLeft: 10,
    height: 100,
    justifyContent: "space-around",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "grey",
    borderRadius: 5,
  },
  oneJobDetailing: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#F29BB2",
    margin: 5,
    marginRight: 10,
    marginLeft: 10,
    height: 100,
    justifyContent: "space-around",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "grey",
    borderRadius: 5,
  },
  timetext: {
    width: 80,
    fontSize: 25,
  },
  carNo: {
    width: 140,
    fontSize: 22,
  },
  serviceType: { width: 100 },
  statusContaine: { width: 50 },
});
